#+TITLE: Emacs komande

* Sadržal :TOC:
- [[#reference][Reference]]
- [[#sažetak][Sažetak]]
- [[#korisničko-sučelje][Korisničko sučelje]]
  - [[#navigacija-dokumentima][Navigacija dokumentima]]
  - [[#baratanje-prozorima-i-panelima][Baratanje prozorima i panelima]]
- [[#org-mode][Org Mode]]
  - [[#osnovna-sintaksa][Osnovna sintaksa]]
  - [[#tablice][Tablice]]
  - [[#kretnje][Kretnje]]
  - [[#org-babel][Org Babel]]
- [[#suradnja-s-vimom][Suradnja s Vimom]]

* Reference
Najprvo treba pregledati github [[https://github.com/doomemacs/doomemacs/blob/master/docs/index.org][dokumentaciju]] i [[https://discourse.doomemacs.org/c/guides/5][službenu dokumentaciju]] za Doom Emcas.

Nakon toga se pažnja može posvetiti tutorialima. Većinu sam ih pronašao preko Doomove dokumentacije.
    + DistroTube
    + Zaiste Programming

* Sažetak
==Emacs== dijeli posao baratanja sa dokumentima i prozorima kroz nekoliko boljki:
     + ~buffer~ - /ono štoje tvoreno/; blo kakav prokrenuti program, bilo da je za čitanje datoteka (/text editor/), bilo da je za bilo što drugo (dired, magit...)
       + obično jedan buffer zauzme jedan prozor
     + ~window~ - okvir u kojem se može vrtiti buffer (obično zvan /pane/).
       + može ih biti više u jednom ekranu (/split/) ili može uzimati cijeli ekran
     + ~workspace~ - je set otvorenih buffera i prozora. Može ih se otvarati koliko se želi i/ili skakati među otvorenima s =<Leader><Tab>=
     + ~project~ - /projekti/ su direktoriji koji sadrže neke uobičajene projektne datoteke ili direktorije (~.git~, ~.hg~...) i otkriveni su po automatizmu te su dostupni kroz =<Leader>pp=, a ako se želi neki dodatan direktorij učiniti "projektom", može se unutar njega smjestiti dadoteka ~.projectile~
     + ~bookmark~ - omogućava brzo skakanje do dokumenta. Glavni prečac je =<Leader><Return>=.
     + ~session~ - koliko znam ne može se ručno spremiti, ali se može povratiti prethodni s =<Leader>ql=

* Korisničko sučelje
** Navigacija dokumentima
  + =<Leader><Leader>= otvara /dired/ iliti Explorer krećući od ~root~ direktorija projekta
  + =<Leader>.= otvara /dired/ iliti Explorer
  + =<Leader>fP= otvara popis konfiguracijskih datoteka
  + =<Leader>fr= otvara popis nedavno otvorenih datoteka

*** Dired i Treemacs
Emacs u startu nudi nekoliko file explorera

**** Osnovni file explorer (bezimen (?), ugrađen)
+ u načelu funkvionira kao ~fzf~
+ otvara ga =<Leader>.=

**** Dired (Directory Editor, ugrađen)
+ omogućuje jednostavnu navigaciju Vim komandamazkretnje (=j=, =k=, =h=, =l=)
+ =(= pali/gasi ispis (meta) detalja u popisu datoteka
+ =<Return>= je za ulazak u dirktorije (otvaranje datoteka), a =-= je za izlazak iz direktorija
+ =+= je za stvaranje dirktorija, a =<Leader>.= omogućava stvaranje i otvaranje nove datoteke
+ =m= je za selekciju stavke
+ =d= je za selekciju stavke za brisnje
+ =x= je za ksekuciju selekcije (bilo otvaranje, bilo brisanje)

**** Treemacs
+ osnovni prečac za otvaranje zatvaranje je =<Leader>op=
** Baratanje prozorima i panelima
  + =<Leader>b{}= je za /buffere/ (prozore, tabove...)
    + =b= je za dobiti popis otvorenih dokumenata (=B= je za vidjeti i neke sistemske buffere, =<Leader>= za vidjeti i skrivene)
      + =<Leader>,= je kratica za =<Leader>bb=
    + =n= je za otvaranje novog buffera
    + =<= i =>= su za otvaranje idućeg/prethodnog
    + =k= je za gašenje aktivnog buffera
  + =<Leader>w{}= je za panele (/panes/) - uglavnom su svi u Doom-u preslika Vimovih (=<C-w>{}= komandi)
    + =s= i =v= su za otvaranje novih panela
    + =w= je za selektiranje idućeg panela
    + =c= ili =q= je za zatvaranje panela
  + =<Leader>qr= je za restartanje Emacsa, ali meni ne radi jer pokrećem Emacs kroz =doom run=

* Org Mode
Iako postoji broj aplikacija za uređivanje Org datoteka (prvenstveno Logseq), sve ove bilješke ću pisati za rad u Emacs-u jer je tamo Org Mode najbolje implementiran i to ću još ograničeno samo na /evil mode/ kakav je prisutan u Spacemacsu ili Doom Emacsu.

Za sve upute o /Org Modu/ može se unutar Emacsa lupiti komanda =M-x org-info=
Ostale upute se mogu potražiti preko prečca =<Leader>ds= (documentation search)

** Osnovna sintaksa
Uobičajena sintaksa je slična, ali ipak drukčija od markdowna

#+START_SRC conf
      * Naslov prvog stupnja
      ** Naslov drugog stupnja
      *** Naslov trećleg stupnja
      *masno*
      /kurziv/
      _potcrtano_
      +precrtano+
      =code=
      ~verbatim~
      [[https://webstranica][Poveznica]]
      - stavka
      - stavka s brojačem podstavki [0/2] [0%]
        - [ ] stavka s kućicom
        - [ ] =<Return>= bi trebao biti za vrtnju stanja
      - stavka
      - stavka
      - TODO stavka za obaviti se gasi/pali s =<S-Left>= i =<S-Right>=
      - TODO stavka za obaviti se preuređuje s =<Leader>mt=
#+END_SRC
** Uređivanje teksta
    + komanda =<M-t>= premeće riječi lijevo-desno, ovisno o tome gdje je smješten kursor. Ako je kursor smješten na početak riječi, onda će riječ zamijeniti mjesto s riječi prije, a ako je smješten usred riječi ili potkraj, onda joj zamijenjuje mjesto s riječi iza.
      + u Vimu se to postiže s /transwrd/ pluginom.
      + naprednija verzija ovog u Emacsu je [[https://github.com/rejeep/drag-stuff.el][rejeep/drag-stuff.el]]-ov plugin koji sve pomiće pomoću =<M-strjelica>= prečca.
** Tablice
+ tablice rabe uobičajenu sintaksu (kao i markdown), ali momogućuju
 da se
       + s =<C-Return>= stvaraju novi retci i da se s =<Tab>= skače iz čelije u čeliju
       + =<S-Return>= je za kopiranje vrijednosti čelije u novi redak
       + =<Leader>mb-= pretvara redak u thead
       + =<M-(hjkl)>= su za izmjene/pomicanja redaka i stupaca

** Kretnje
+ Pored uobičajenih Vim kretnji, Org Mode omogućava još nekoliko specifično korisnih:
  + =<Tab>= je komanda za otvaranje i zatvaranje naslovnih cjelina
    + =<S-Tab>= je za otvaranje/zatvaranje svih odjednom
  + =gj= i =gk= su za skakanje od naslova do naslova istog stupnja
  + =<C-Return>= daje novi redak istog stupnja u kojem se nalazimo
    + to može biti nova stavka u popisu ili novi naslov istog stupnja nakon cjeline
  + =<M-h>= i =<M-l>= su za mijenjanje stupnja naslova
  + =<M-k>= i =<M-j>= su za zamjene položaja cijelih naslovljenih blokova

** Org Babel
+ osnovna sintaksa za pisanje koda je =#+START_SRC= i =#+END_SRC=, a prečac =<s<Tab>=
+ jednom kada je kod ispisan, =<Enter>= u normalnom modu izvršava blok koda

*** Tangle
+ /Org Bable Tangle/ je mehanizam za prikupljanje koda iz ~.org~ dokumenata i izvoz u druge datoteke
+ osnovni prečac je =<C-c><C-v>t=


* Suradnja s Vimom
Plugini [[https://github.com/jceb/vim-orgmode/blob/master/doc/orgguide.txt][Vim Org-Mode]] ili [[https://github.com/nvim-neorg/neorg][Neorg]] omogućuju otvaranje ~.org~ datoteka u *Vim*-u i simulaciju *Emacs*-ovih mogućnosti, ali nisam siguran koliko su međusobno kompatibilni i zahtijevaju li ubacivanje nekakvih posebnih headera ili metapodataka unutar datoteke
